class DocumentData:
    name = ""
    address = ""
    p_number = ""
    notes = ""
    callsign = ""
    type_data = ""
    modell = ""
    description = ""
    addons = ""
    diagnosis = ""
    year = ""
    month = ""
    day = ""